### ISSUE TITLE
Installing on macOS Catalina

### ISSUE THREAD

**Issue by vmplacco** [alexji/moog17scat#3]
I actually don't think this is an issue, but I thought this would be a good place to have it written for future reference.

I just compiled moog17scat on a fresh macOS Catalina installation. I had two small hiccups:

The `gfortran` I used at first came from `gcc 10.2.0` (from homebrew). When I used this version, I got a few compilation errors on `OpacHydrogen.f`. Instead of messing with the code, I installed an earlier version of `gfortran`, which I knew worked:

    brew install gcc@5

Then, on the Makefile.macdesk I have:
    
    FC = /usr/local/Cellar/gcc\@5/5.5.0_4/bin/gfortran-5 -Wall -fno-range-check -w -ff2c

This compiled everything without errors or warnings.

I also had an error on the AQLIB library, and replacing: `-L$(AQLIB) -laquaterm` with `-L$(AQLIB) -framework AquaTerm` solved the problem.

Thanks!
Vini

**Comment by alexji** [comment]
This is so helpful, thank you!! I will put this in the README
