### ISSUE TITLE
Makeplot.f all commented

### ISSUE THREAD

**Issue by ZusiMichele** [alexji/moog17scat#9]
Hi.
I am using MOOG for stars abundance analysis and I am not able to produce any plot even if I specify it in the configuration file (i.e., .par file). Looking at the sequence of function calls from the Abfind.f I arrive at the function Makeplot.f where I see almost all the lines commented (in particular the ones that call SuperMongo routine). Why? With which call such calls have been substituted? If I remove all the comments and re-compile everything I have the following:

make -f Makefile.macdesk
...
Undefined symbols for architecture x86_64:
  "_sm_alpha_", referenced from:
      _makeplot_ in Makeplot.o
  "_sm_device_", referenced from:
      _makeplot_ in Makeplot.o
      _makeplot_ in Makeplot.o
      _makeplot_ in Makeplot.o
      _makeplot_ in Makeplot.o
  "_sm_erase_", referenced from:
      _makeplot_ in Makeplot.o
  "_sm_gflush_", referenced from:
      _makeplot_ in Makeplot.o
  "_sm_graphics_", referenced from:
      _makeplot_ in Makeplot.o
  "_sm_hardcopy_", referenced from:
      _makeplot_ in Makeplot.o
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status
make: *** [MOOG] Error 1

with the error on the "_sm_alpha_" (and others) call which seems to be missing.
Just for completness I am working on a iMacPro 8-Core Intel Xeon W and MacOs Sonoma 14.6.1. 
Could you help me?

**Comment by alexji** [comment]
This version of MOOG was purposefully edited to remove plotting as we use a
custom plotting tool. If you want the full version I recommend getting it
from Chris Sneden’s website.

**Comment by ZusiMichele** [comment]
Ok, thanks.
